# Generated by Django 2.1.4 on 2018-12-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='firstname',
            field=models.CharField(default=('mohan', 'kumar'), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='lastname',
            field=models.CharField(default=('mohan', 'kumar', 'mohan', 'kumar'), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='passwd',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
